import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" flex flex-col min-h-screen justify-between">
          <div className=" border-black border-b-4 bg-lime-100 h-32">
            <Navbar />
          </div>
          <div className=" h-auto">{children}</div>
          <div className="bg-blue-200 h-32 mt-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
